/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import reponsitory.ThongkeReponsitory;

/**
 *
 * @author Asus
 */
public class JpanelThongKe extends javax.swing.JPanel {

    ThongkeReponsitory TKR = new ThongkeReponsitory();

    /**
     * Creates new form JpanelThongKe
     */
    public JpanelThongKe() {
        initComponents();
        bieudo();
        thongkengay();
        thongkeThang();
        tongdoanhthu();
        SoHoaDon();
        fillTableThongKeNam(TKR.danhSachDoanhThuNam());
        Date month = new Date();
        SimpleDateFormat fomaterMonth = new SimpleDateFormat("MM");
        String nowString = fomaterMonth.format(month);

        Date day = new Date();
        SimpleDateFormat fomaterDay = new SimpleDateFormat("dd-MM-yyyy");
        String dayString = fomaterDay.format(day);

        lblTieuDeDoanhThuThang.setText("Doanh thu tháng " + nowString);
        lblTieuDeDoanhThuNgay1.setText("Doanh thu ngày " + dayString);
        lblTieuDeSoHoaDon.setText("Số hóa đơn bán tháng " + nowString);

        setLBLALL(lblDoanhThuNgay1, TKR.doanhthungay() == null ? "0" : formatCash(TKR.doanhthungay()) );
        setLBLALL(lblDoanhThuThang, TKR.doanhThuThang() == null ? "0" :  formatCash(TKR.doanhThuThang()));
        setLBLALL(lblTongDoanhThu, formatCash(TKR.tongDoanhThu()));
        setLBLALL(lblSoHoaDon, TKR.SoHoaDon().toString() == null ? "0" : TKR.SoHoaDon().toString());
    }

    private void setLBLALL(JLabel lb, String values) {
        lb.setText(values);
    }

    public void thongkengay() {
       
        lblDoanhThuNgay1.setText(formatCash(TKR.doanhthungay()));
    }

    public void thongkeThang() {
        lblDoanhThuThang.setText(formatCash(TKR.doanhThuThang()));
    }

    public void tongdoanhthu() {
        lblTongDoanhThu.setText(formatCash(TKR.tongDoanhThu()));
    }

    public void SoHoaDon() {
        lblSoHoaDon.setText(TKR.SoHoaDon().toString());
    }
    private void fillTableThongKeNam(List<Object[]> list) {
        DefaultTableModel model = (DefaultTableModel) tblThongKeNam.getModel();
        model.setRowCount(0);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
    public static void main(String[] args) {
        JFrame frame = new JFrame("Quản lý sản phẩm view");

        JpanelThongKe tKV = new JpanelThongKe();
        frame.add(tKV);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tabsThongKe = new javax.swing.JTabbedPane();
        jpnThongKeDoanhThu = new javax.swing.JPanel();
        jpnDoanhThuNgay = new javax.swing.JPanel();
        lblTieuDeSoHoaDon = new javax.swing.JLabel();
        lblSoHoaDon = new javax.swing.JLabel();
        jpnDoanThuThang = new javax.swing.JPanel();
        lblTieuDeDoanhThuThang = new javax.swing.JLabel();
        lblDoanhThuThang = new javax.swing.JLabel();
        jpnTongDoanhThu = new javax.swing.JPanel();
        lbTitle7 = new javax.swing.JLabel();
        lblTongDoanhThu = new javax.swing.JLabel();
        jpnThongKeTheoNam = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeNam = new javax.swing.JTable();
        JpnBieuDo = new javax.swing.JPanel();
        jpnDoanhThuNgay1 = new javax.swing.JPanel();
        lblTieuDeDoanhThuNgay1 = new javax.swing.JLabel();
        lblDoanhThuNgay1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1145, 683));

        tabsThongKe.setBackground(new java.awt.Color(255, 255, 255));
        tabsThongKe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THỐNG KÊ DOANH THU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jpnThongKeDoanhThu.setBackground(new java.awt.Color(255, 255, 255));

        jpnDoanhThuNgay.setBackground(new java.awt.Color(255, 255, 255));
        jpnDoanhThuNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTieuDeSoHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDeSoHoaDon.setText("Số Hóa Đơn Đã Bán Tháng ");

        lblSoHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSoHoaDon.setForeground(new java.awt.Color(255, 51, 0));
        lblSoHoaDon.setText("Values");

        javax.swing.GroupLayout jpnDoanhThuNgayLayout = new javax.swing.GroupLayout(jpnDoanhThuNgay);
        jpnDoanhThuNgay.setLayout(jpnDoanhThuNgayLayout);
        jpnDoanhThuNgayLayout.setHorizontalGroup(
            jpnDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuNgayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTieuDeSoHoaDon)
                    .addComponent(lblSoHoaDon))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jpnDoanhThuNgayLayout.setVerticalGroup(
            jpnDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuNgayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDeSoHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoHoaDon)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnDoanThuThang.setBackground(new java.awt.Color(255, 255, 255));
        jpnDoanThuThang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTieuDeDoanhThuThang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDeDoanhThuThang.setText("Doanh thu tháng");

        lblDoanhThuThang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDoanhThuThang.setForeground(new java.awt.Color(255, 51, 0));
        lblDoanhThuThang.setText("Values");

        javax.swing.GroupLayout jpnDoanThuThangLayout = new javax.swing.GroupLayout(jpnDoanThuThang);
        jpnDoanThuThang.setLayout(jpnDoanThuThangLayout);
        jpnDoanThuThangLayout.setHorizontalGroup(
            jpnDoanThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanThuThangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDoanThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTieuDeDoanhThuThang)
                    .addComponent(lblDoanhThuThang))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jpnDoanThuThangLayout.setVerticalGroup(
            jpnDoanThuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanThuThangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDeDoanhThuThang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDoanhThuThang)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnTongDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        jpnTongDoanhThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbTitle7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitle7.setText("Tổng doanh thu");

        lblTongDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTongDoanhThu.setForeground(new java.awt.Color(255, 51, 0));
        lblTongDoanhThu.setText("Values");

        javax.swing.GroupLayout jpnTongDoanhThuLayout = new javax.swing.GroupLayout(jpnTongDoanhThu);
        jpnTongDoanhThu.setLayout(jpnTongDoanhThuLayout);
        jpnTongDoanhThuLayout.setHorizontalGroup(
            jpnTongDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTongDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTongDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle7)
                    .addComponent(lblTongDoanhThu))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jpnTongDoanhThuLayout.setVerticalGroup(
            jpnTongDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTongDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongDoanhThu)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnThongKeTheoNam.setBackground(new java.awt.Color(255, 255, 255));
        jpnThongKeTheoNam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thống kê theo năm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jpnThongKeTheoNam.setPreferredSize(new java.awt.Dimension(478, 200));

        tblThongKeNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Năm", "Doanh thu", "Tháng doanh thu cao nhất", "Tháng doanh thu thấp nhất", "Doanh thu trung bình tháng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblThongKeNam);

        javax.swing.GroupLayout jpnThongKeTheoNamLayout = new javax.swing.GroupLayout(jpnThongKeTheoNam);
        jpnThongKeTheoNam.setLayout(jpnThongKeTheoNamLayout);
        jpnThongKeTheoNamLayout.setHorizontalGroup(
            jpnThongKeTheoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeTheoNamLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jpnThongKeTheoNamLayout.setVerticalGroup(
            jpnThongKeTheoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeTheoNamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JpnBieuDo.setLayout(new java.awt.BorderLayout());

        jpnDoanhThuNgay1.setBackground(new java.awt.Color(255, 255, 255));
        jpnDoanhThuNgay1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTieuDeDoanhThuNgay1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTieuDeDoanhThuNgay1.setText("Doanh thu ngày dd-MM-yyyy");

        lblDoanhThuNgay1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDoanhThuNgay1.setForeground(new java.awt.Color(255, 51, 0));
        lblDoanhThuNgay1.setText("Values");

        javax.swing.GroupLayout jpnDoanhThuNgay1Layout = new javax.swing.GroupLayout(jpnDoanhThuNgay1);
        jpnDoanhThuNgay1.setLayout(jpnDoanhThuNgay1Layout);
        jpnDoanhThuNgay1Layout.setHorizontalGroup(
            jpnDoanhThuNgay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuNgay1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDoanhThuNgay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTieuDeDoanhThuNgay1)
                    .addComponent(lblDoanhThuNgay1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDoanhThuNgay1Layout.setVerticalGroup(
            jpnDoanhThuNgay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuNgay1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDeDoanhThuNgay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDoanhThuNgay1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnThongKeDoanhThuLayout = new javax.swing.GroupLayout(jpnThongKeDoanhThu);
        jpnThongKeDoanhThu.setLayout(jpnThongKeDoanhThuLayout);
        jpnThongKeDoanhThuLayout.setHorizontalGroup(
            jpnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeDoanhThuLayout.createSequentialGroup()
                .addGroup(jpnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongKeDoanhThuLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(JpnBieuDo, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnThongKeDoanhThuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnDoanhThuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnDoanhThuNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnDoanThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeDoanhThuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnThongKeTheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnThongKeDoanhThuLayout.setVerticalGroup(
            jpnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeDoanhThuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnDoanThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnDoanhThuNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnDoanhThuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JpnBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnThongKeTheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        tabsThongKe.addTab("Doanh thu", jpnThongKeDoanhThu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsThongKe))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tabsThongKe)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
 private String formatCash(Double price) {
        try {
            NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
            String formated = currencyFormatter.format(price);
            return formated;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình format");
            return "";
        }

    }

    //Hàm này có tác dụng format lại tiền
    private String formatCash(float price) {
        try {
            NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
            String formated = currencyFormatter.format(price);
            return formated;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình format");
            return "";
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        dataset.setValue(80, "Marks", "Student");
//         dataset.setValue(40, "Marks", "Student1");
//          dataset.setValue(60, "Marks", "Student2");
//           dataset.setValue(70, "Marks", "Student3");
//           JFreeChart chart = ChartFactory.createBarChart("Phieu giam gia", "Name", "Marsk", dataset, PlotOrientation.VERTICAL, false, true, false);
//          CategoryPlot p= chart.getCategoryPlot();
//          p.setRangeGridlinePaint(Color.black);
//          ChartFrame frame = new ChartFrame("HEHEHE", chart);
//          frame.setVisible(true);
//          frame.setSize(450, 350);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void bieudo() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(TKR.doanhThuThang(1, 2024), "Marks", "Tháng 1");
        dataset.setValue(TKR.doanhThuThang(2, 2024), "Marks", "Tháng 2");
        dataset.setValue(TKR.doanhThuThang(3, 2024), "Marks", "Tháng 3");
        dataset.setValue(TKR.doanhThuThang(4, 2024), "Marks", "Tháng 4");
        dataset.setValue(TKR.doanhThuThang(5, 2024), "Marks", "Tháng 5");
        dataset.setValue(TKR.doanhThuThang(6, 2024), "Marks", "Tháng 6");
        dataset.setValue(TKR.doanhThuThang(7, 2024), "Marks", "Tháng 7");
        dataset.setValue(TKR.doanhThuThang(8, 2024), "Marks", "Tháng 8");
        dataset.setValue(TKR.doanhThuThang(9, 2024), "Marks", "Tháng 9");
        dataset.setValue(TKR.doanhThuThang(10, 2024), "Marks", "Tháng 10");
        dataset.setValue(TKR.doanhThuThang(11, 2024), "Marks", "Tháng 11");
        dataset.setValue(TKR.doanhThuThang(12, 2024), "Marks", "Tháng 11");

        JFreeChart chart = ChartFactory.createLineChart("Doanh số bán hàng", "Doanh số bán hàng", "VND đồng", dataset, PlotOrientation.VERTICAL, false, true, false);

        CategoryPlot p = chart.getCategoryPlot();
        p.setBackgroundPaint(Color.white);
        p.setRangeGridlinePaint(Color.black);
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) p.getRenderer();
        Color lineChartColor = new Color(204, 0, 51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
//          ChartFrame frame = new ChartFrame("PHIẾU GIẢM GIÁ", chart);
//          frame.setVisible(true);
//          frame.setSize(450, 350);
        ChartPanel panelTK = new ChartPanel(chart);
        JpnBieuDo.removeAll();
        JpnBieuDo.add(panelTK, BorderLayout.CENTER);
        JpnBieuDo.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnBieuDo;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnDoanThuThang;
    private javax.swing.JPanel jpnDoanhThuNgay;
    private javax.swing.JPanel jpnDoanhThuNgay1;
    private javax.swing.JPanel jpnThongKeDoanhThu;
    private javax.swing.JPanel jpnThongKeTheoNam;
    private javax.swing.JPanel jpnTongDoanhThu;
    private javax.swing.JLabel lbTitle7;
    private javax.swing.JLabel lblDoanhThuNgay1;
    private javax.swing.JLabel lblDoanhThuThang;
    private javax.swing.JLabel lblSoHoaDon;
    private javax.swing.JLabel lblTieuDeDoanhThuNgay1;
    private javax.swing.JLabel lblTieuDeDoanhThuThang;
    private javax.swing.JLabel lblTieuDeSoHoaDon;
    private javax.swing.JLabel lblTongDoanhThu;
    private javax.swing.JTabbedPane tabsThongKe;
    private javax.swing.JTable tblThongKeNam;
    // End of variables declaration//GEN-END:variables
}
