/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1041;

import config.XLogin;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import view.JPanelSanPham;
import view.JpanelBanHang;
import view.JpanelHoaDon1;
import view.JpanelKhachHang1;
import view.JpanelNhanVien;
import view.JpanelPhieuGiamGia;
import view.JpanelThongKe;
import view.JpanelTrangChu;
import view.LoginJDialog;
import view.login;

/**
 *
 * @author laptop
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        LoginJDialog n = new LoginJDialog(this, true);
        n.setVisible(true);
        if (XLogin.daDangNhap()) {

            initComponents();
            setLocationRelativeTo(null);
            setTitle("Ứng dụng bán vợt cầu lông YONEX - Nhóm 4");
            URL url = Dashboard.class.getResource("icon/LOGO2.png");
            setIconImage(new ImageIcon(url).getImage());
            dongHo();
            String role = XLogin.user.isVaiTro() ? "Quản lý" : "Nhân Viên";
            lblThongtinDangNhap.setText(XLogin.user.getHoTen() + " - " + "Chức vụ: " + role);
        } else {
            System.exit(0);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFameChinh = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jPanelTrangChu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSanPham = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelBanhHang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelPhieuGiamGia = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelKhachHang = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelNhanVien = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JpanelThongKe = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        JpanelDangXuat = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        JpanelRoot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblThongtinDangNhap = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblThoiGian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setFocusable(false);
        setResizable(false);

        JFameChinh.setBackground(new java.awt.Color(255, 255, 255));

        sidepane.setBackground(new java.awt.Color(255, 188, 207));

        jPanelTrangChu.setBackground(new java.awt.Color(255, 188, 207));
        jPanelTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTrangChuMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 188, 207));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/home.png"))); // NOI18N
        jLabel2.setText("    Trang chủ");

        javax.swing.GroupLayout jPanelTrangChuLayout = new javax.swing.GroupLayout(jPanelTrangChu);
        jPanelTrangChu.setLayout(jPanelTrangChuLayout);
        jPanelTrangChuLayout.setHorizontalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTrangChuLayout.setVerticalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanelSanPham.setBackground(new java.awt.Color(255, 188, 207));
        jPanelSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSanPhamMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/caulong16.png"))); // NOI18N
        jLabel4.setText("    Sản phẩm");

        javax.swing.GroupLayout jPanelSanPhamLayout = new javax.swing.GroupLayout(jPanelSanPham);
        jPanelSanPham.setLayout(jPanelSanPhamLayout);
        jPanelSanPhamLayout.setHorizontalGroup(
            jPanelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSanPhamLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSanPhamLayout.setVerticalGroup(
            jPanelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanelBanhHang.setBackground(new java.awt.Color(255, 188, 207));
        jPanelBanhHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBanhHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBanhHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBanhHangMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/shopping-cart.png"))); // NOI18N
        jLabel8.setText("    Bán hàng");

        javax.swing.GroupLayout jPanelBanhHangLayout = new javax.swing.GroupLayout(jPanelBanhHang);
        jPanelBanhHang.setLayout(jPanelBanhHangLayout);
        jPanelBanhHangLayout.setHorizontalGroup(
            jPanelBanhHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBanhHangLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBanhHangLayout.setVerticalGroup(
            jPanelBanhHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanelHoaDon.setBackground(new java.awt.Color(255, 188, 207));
        jPanelHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelHoaDonMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/bill.png"))); // NOI18N
        jLabel10.setText("    Hóa đơn");

        javax.swing.GroupLayout jPanelHoaDonLayout = new javax.swing.GroupLayout(jPanelHoaDon);
        jPanelHoaDon.setLayout(jPanelHoaDonLayout);
        jPanelHoaDonLayout.setHorizontalGroup(
            jPanelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHoaDonLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHoaDonLayout.setVerticalGroup(
            jPanelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanelPhieuGiamGia.setBackground(new java.awt.Color(255, 188, 207));
        jPanelPhieuGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPhieuGiamGiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPhieuGiamGiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPhieuGiamGiaMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/promo-code.png"))); // NOI18N
        jLabel12.setText("    Phiếu giảm giá");

        javax.swing.GroupLayout jPanelPhieuGiamGiaLayout = new javax.swing.GroupLayout(jPanelPhieuGiamGia);
        jPanelPhieuGiamGia.setLayout(jPanelPhieuGiamGiaLayout);
        jPanelPhieuGiamGiaLayout.setHorizontalGroup(
            jPanelPhieuGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhieuGiamGiaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel12)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelPhieuGiamGiaLayout.setVerticalGroup(
            jPanelPhieuGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanelKhachHang.setBackground(new java.awt.Color(255, 188, 207));
        jPanelKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelKhachHangMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/people.png"))); // NOI18N
        jLabel14.setText("    Khách hàng");

        javax.swing.GroupLayout jPanelKhachHangLayout = new javax.swing.GroupLayout(jPanelKhachHang);
        jPanelKhachHang.setLayout(jPanelKhachHangLayout);
        jPanelKhachHangLayout.setHorizontalGroup(
            jPanelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhachHangLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKhachHangLayout.setVerticalGroup(
            jPanelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanelNhanVien.setBackground(new java.awt.Color(255, 188, 207));
        jPanelNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNhanVienMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/customer.png"))); // NOI18N
        jLabel18.setText("    Nhân viên");

        javax.swing.GroupLayout jPanelNhanVienLayout = new javax.swing.GroupLayout(jPanelNhanVien);
        jPanelNhanVien.setLayout(jPanelNhanVienLayout);
        jPanelNhanVienLayout.setHorizontalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNhanVienLayout.setVerticalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/LOGO2.png"))); // NOI18N

        jLabel19.setBackground(new java.awt.Color(255, 188, 207));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("YONEX");

        JpanelThongKe.setBackground(new java.awt.Color(255, 188, 207));
        JpanelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpanelThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpanelThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpanelThongKeMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/trend.png"))); // NOI18N
        jLabel20.setText("    Thống kê");

        javax.swing.GroupLayout JpanelThongKeLayout = new javax.swing.GroupLayout(JpanelThongKe);
        JpanelThongKe.setLayout(JpanelThongKeLayout);
        JpanelThongKeLayout.setHorizontalGroup(
            JpanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelThongKeLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        JpanelThongKeLayout.setVerticalGroup(
            JpanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        JpanelDangXuat.setBackground(new java.awt.Color(255, 188, 207));
        JpanelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpanelDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpanelDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpanelDangXuatMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Đăng xuất");

        javax.swing.GroupLayout JpanelDangXuatLayout = new javax.swing.GroupLayout(JpanelDangXuat);
        JpanelDangXuat.setLayout(JpanelDangXuatLayout);
        JpanelDangXuatLayout.setHorizontalGroup(
            JpanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelDangXuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        JpanelDangXuatLayout.setVerticalGroup(
            JpanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelTrangChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBanhHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPhieuGiamGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelThongKe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepaneLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBanhHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPhieuGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanelBanhHang, jPanelHoaDon, jPanelKhachHang, jPanelNhanVien, jPanelPhieuGiamGia, jPanelSanPham, jPanelTrangChu});

        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/menu.png"))); // NOI18N

        JpanelRoot.setBackground(new java.awt.Color(255, 255, 255));
        JpanelRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JpanelRoot.setFocusCycleRoot(true);
        JpanelRoot.setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("TRANG CHỦ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel5.setText("YONEX");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("UY TÍN - CAO CẤP - TẬN TÂM");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1041/icon/vot_cau_long_yonex_astrox_66_chinh_hang_yonex.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(63, 63, 63)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 352, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addGap(33, 33, 33)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpanelRootLayout = new javax.swing.GroupLayout(JpanelRoot);
        JpanelRoot.setLayout(JpanelRootLayout);
        JpanelRootLayout.setHorizontalGroup(
            JpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1217, Short.MAX_VALUE)
            .addGroup(JpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelRootLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JpanelRootLayout.setVerticalGroup(
            JpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(JpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelRootLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblThongtinDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThongtinDangNhap.setText("Tên người dùng - Chức vụ: ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThoiGian.setText("Thời gian");

        javax.swing.GroupLayout JFameChinhLayout = new javax.swing.GroupLayout(JFameChinh);
        JFameChinh.setLayout(JFameChinhLayout);
        JFameChinhLayout.setHorizontalGroup(
            JFameChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFameChinhLayout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JFameChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JFameChinhLayout.createSequentialGroup()
                        .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblThongtinDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(JFameChinhLayout.createSequentialGroup()
                        .addComponent(JpanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JFameChinhLayout.setVerticalGroup(
            JFameChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFameChinhLayout.createSequentialGroup()
                .addGroup(JFameChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JFameChinhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JFameChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFameChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblThongtinDangNhap)
                                .addComponent(lblThoiGian))
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JFameChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JFameChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrangChuMouseEntered
        // TODO add your handling code here:
        jPanelTrangChu.setBackground(setMau(211, 211, 211));

    }//GEN-LAST:event_jPanelTrangChuMouseEntered

    private void jPanelTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrangChuMouseExited
        // TODO add your handling code here:
        jPanelTrangChu.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelTrangChuMouseExited

    private void jPanelTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTrangChuMouseClicked
        // TODO add your handling code here:
        node = new JpanelTrangChu();
        setView(JpanelRoot);

    }//GEN-LAST:event_jPanelTrangChuMouseClicked

    private void jPanelBanhHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBanhHangMouseClicked
        // TODO add your handling code here:
        if (XLogin.daDangNhap()) {
            node = new JpanelBanHang();
            setView(JpanelRoot);
        } else {
            JOptionPane.showMessageDialog(this, "Chưa đăng nhập!");
        }

    }//GEN-LAST:event_jPanelBanhHangMouseClicked

    private void jPanelBanhHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBanhHangMouseEntered
        // TODO add your handling code here:
        jPanelBanhHang.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_jPanelBanhHangMouseEntered

    private void jPanelBanhHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBanhHangMouseExited
        // TODO add your handling code here:
        jPanelBanhHang.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelBanhHangMouseExited

    private void jPanelHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoaDonMouseEntered
        // TODO add your handling code here:
        jPanelHoaDon.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_jPanelHoaDonMouseEntered

    private void jPanelHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoaDonMouseExited
        // TODO add your handling code here:
        jPanelHoaDon.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelHoaDonMouseExited

    private void jPanelSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanPhamMouseEntered
        // TODO add your handling code here:
        jPanelSanPham.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_jPanelSanPhamMouseEntered

    private void jPanelSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanPhamMouseExited
        // TODO add your handling code here:
        jPanelSanPham.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelSanPhamMouseExited

    private void jPanelKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKhachHangMouseEntered
        // TODO add your handling code here:
        jPanelKhachHang.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_jPanelKhachHangMouseEntered

    private void jPanelKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKhachHangMouseExited
        // TODO add your handling code here:
        jPanelKhachHang.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelKhachHangMouseExited

    private void jPanelNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanVienMouseEntered
        // TODO add your handling code here:
        jPanelNhanVien.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_jPanelNhanVienMouseEntered

    private void jPanelNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanVienMouseExited
        // TODO add your handling code here:
        jPanelNhanVien.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelNhanVienMouseExited

    private void jPanelNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanVienMouseClicked
        // TODO add your handling code here:
        node = new JpanelNhanVien();
        setView(JpanelRoot);

    }//GEN-LAST:event_jPanelNhanVienMouseClicked

    private void jPanelPhieuGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPhieuGiamGiaMouseClicked
        // TODO add your handling code here:
        node = new JpanelPhieuGiamGia();
        setView(JpanelRoot);
    }//GEN-LAST:event_jPanelPhieuGiamGiaMouseClicked

    private void jPanelPhieuGiamGiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPhieuGiamGiaMouseEntered
        // TODO add your handling code here:
        jPanelPhieuGiamGia.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_jPanelPhieuGiamGiaMouseEntered

    private void jPanelPhieuGiamGiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPhieuGiamGiaMouseExited
        // TODO add your handling code here:
        jPanelPhieuGiamGia.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_jPanelPhieuGiamGiaMouseExited

    private void jPanelKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKhachHangMouseClicked
        // TODO add your handling code here:
        node = new JpanelKhachHang1();
        setView(JpanelRoot);
    }//GEN-LAST:event_jPanelKhachHangMouseClicked

    private void jPanelHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoaDonMouseClicked
        // TODO add your handling code here:
        node = new JpanelHoaDon1();
        setView(JpanelRoot);
    }//GEN-LAST:event_jPanelHoaDonMouseClicked

    private void JpanelThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelThongKeMouseClicked
        // TODO add your handling code here:

        if (XLogin.phanQuyen()) {
            node = new JpanelThongKe();
            setView(JpanelRoot);
        } else {
            JOptionPane.showMessageDialog(this, "Không đủ quyền xem thống kê");
        }


    }//GEN-LAST:event_JpanelThongKeMouseClicked

    private void JpanelThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelThongKeMouseEntered
        // TODO add your handling code here:
        JpanelThongKe.setBackground(setMau(211, 211, 211));

    }//GEN-LAST:event_JpanelThongKeMouseEntered

    private void JpanelThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelThongKeMouseExited
        // TODO add your handling code here:
        JpanelThongKe.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_JpanelThongKeMouseExited

    private void jPanelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSanPhamMouseClicked
        // TODO add your handling code here:
        node = new JPanelSanPham();
        setView(JpanelRoot);
    }//GEN-LAST:event_jPanelSanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JpanelDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelDangXuatMouseClicked
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_JpanelDangXuatMouseClicked
 private void logout() {
//         Đóng cửa sổ hiện tại
        dispose();
        XLogin.dangXuat();
        // Hiển thị màn hình đăng nhập
        Dashboard db = new Dashboard();
        db.setVisible(true);

        JpanelDangXuat.setVisible(false);

       
    }
    private void JpanelDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelDangXuatMouseEntered
        // TODO add your handling code here:
         JpanelDangXuat.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_JpanelDangXuatMouseEntered

    private void JpanelDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelDangXuatMouseExited
        // TODO add your handling code here:
         JpanelDangXuat.setBackground(setMau(255, 188, 207));
    }//GEN-LAST:event_JpanelDangXuatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });

    }

    private void dongHo() {
        Thread t = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                    Date now = new Date();
                    SimpleDateFormat fomater = new SimpleDateFormat("dd-MM-yyyy | hh:mm:ss aa");
                    String time = fomater.format(now);
                    lblThoiGian.setText(time);
                }
            }
        };
        t.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JFameChinh;
    private javax.swing.JPanel JpanelDangXuat;
    private javax.swing.JPanel JpanelRoot;
    private javax.swing.JPanel JpanelThongKe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBanhHang;
    private javax.swing.JPanel jPanelHoaDon;
    private javax.swing.JPanel jPanelKhachHang;
    private javax.swing.JPanel jPanelNhanVien;
    private javax.swing.JPanel jPanelPhieuGiamGia;
    private javax.swing.JPanel jPanelSanPham;
    private javax.swing.JPanel jPanelTrangChu;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblThongtinDangNhap;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
    Color setMau(int red, int green, int blue) {
        return new Color(red, green, blue);

    }
    public JPanel node;

    private void setView(JPanel root) {
        root.removeAll();
        root.setLayout(new BorderLayout());
        root.add(node);
        root.validate();
        root.repaint();

    }

}
